[project]
name = "validate-semantic-karnel"
version = "0.1.0"
description = ""
authors = [
    {name = "tokihiko-tsurumoto",email = "tokihiko-tsurumoto@cybozu.co.jp"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "semantic-kernel (>=1.26.1,<2.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.11,<4.0.0"